[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para optimización de performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
# Headers para assets estáticos (CSS, JS, imágenes)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Headers para HTML (sin cache para siempre mostrar última versión)
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Headers para Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    
# Headers para imágenes y fuentes
[[headers]]
  for = "/*.{jpg,jpeg,png,gif,webp,svg,woff,woff2}"
  [headers.values]
    Cache-Control = "public, max-age=604800, immutable"

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"


